version: '2.1'
services:
    redis:
        image: redis:latest
        # command: redis-server --requirepass redispass
        restart: always

    postgres:
        build:
            context: ./services/postgres
        env_file: 
            - ./services/postgres/postgres.env

        volumes:
            - pgdata:/var/lib/postgresql/data

        restart: always

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - 5050:80
        env_file: 
            - ./services/pgadmin/pgadmin.env
        restart: unless-stopped

    webserver:
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - postgres
            - redis
        env_file: 
            - ./services/airflow/airflow.env
        volumes:
            - ./jobs/dags:/usr/local/airflow/dags
            - ./jobs/logs/airflow:/opt/airflow/logs
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    # flower:
    #     build:
    #         context: ./services/airflow
    #     restart: always
    #     depends_on:
    #         - redis
    #     environment:
    #         - EXECUTOR=Celery
    #         # - REDIS_PASSWORD=redispass
    #     ports:
    #         - "5555:5555"
    #     command: flower
    #     container_name: flower

    scheduler:
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./jobs/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        env_file: 
            - ./services/airflow/airflow.env
        command: scheduler

    worker:
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./jobs/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./airflow/plugins:/usr/local/airflow/plugins
        env_file: 
            - ./services/airflow/airflow.env
        command: worker


volumes:
    pgdata:
        external: true
