version: '3.3'
services:
    redis:
        container_name: redis
        image: redis:latest
        # command: redis-server --requirepass redispass
        restart: always

    redisinsight:
      container_name: redisUI
      image: redislabs/redisinsight
      ports:
          - 8001:8001
      depends_on:
          - redis


    postgres:
        container_name: postgres
        build:
            context: ./services/postgres
        env_file: 
            - ./services/postgres/postgres.env
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always


    pgadmin:
        container_name: pgUI
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - 5050:80
        env_file: 
            - ./services/pgadmin/pgadmin.env
        restart: unless-stopped
    
    minio:
        container_name: minio
        image: minio/minio:latest
        ports:
            - 9000:9000
        command: server /data
        env_file: 
            - ./services/minio/minio.env
        volumes: 
            - ./services/minio/data:/data

    webserver:
        container_name: webserver
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - postgres
            - redis
        env_file: 
            - ./services/airflow/airflow.env
        volumes:
            - ./jobs/dags:/usr/local/airflow/dags
            - ./jobs/logs/airflow:/opt/airflow/logs
            # Uncomment to include custom plugins
            # - ./services/airflow/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
        container_name: scheduler
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./jobs/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./services/airflow/plugins:/usr/local/airflow/plugins
        env_file: 
            - ./services/airflow/airflow.env
        command: scheduler

    worker:
        container_name: worker
        build:
            context: ./services/airflow
        restart: always
        depends_on:
            - webserver
            - scheduler
        volumes:
            - ./jobs/dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./services/airflow/plugins:/usr/local/airflow/plugins
        env_file: 
            - ./services/airflow/airflow.env
        command: celery worker


volumes:
    pgdata:
        external: true
